#!/bin/bash
export MICROMEGAS_HOME=$HOME/micromegas
export SCRIPTS_PATH=$MICROMEGAS_HOME/scripts
export MICROMEGAS_SCRIPTS_PATH=$MICROMEGAS_HOME/scripts
export MICROMEGAS_SIMULATION_PATH="$MICROMEGAS_HOME/simulation"
export MICROMEGAS_OUTPUT_PATH="/etapfs03/atlashpc/fneuhaus/micromegas"
export MICROMEGAS_RUN_PATH="$MICROMEGAS_HOME/simulation/runs/"


export PARTICLECONVERSION_EXEC=$MICROMEGAS_HOME/simulation/particleconversion/build/particleconversion
export DRIFT_EXEC=$MICROMEGAS_HOME/simulation/drift/drift
export AVALANCHE_EXEC=$MICROMEGAS_HOME/simulation/avalanche/avalanche

# Load cmake
module load devel/CMake/3.8.0-intel-2017.02

# Initialize ROOT
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh >/dev/null 2>&1
lsetup "root 5.34.25-x86_64-slc6-gcc48-opt" >/dev/null 2>&1

# Initialize python
source $HOME/software/python/bin/activate

# Initialize GCC
module load compiler/GCC/4.8.4
export CC=$(which gcc)
export CXX=$(which g++)

# Initialize GEANT4
module load own/geant4/current

# Initialize garfield
module load own/garfield/current

# Elmer
module load own/elmerfem/current

# gmsh
module load own/gmsh/current

# Pythonpath
export PYTHONPATH=$MICROMEGAS_SIMULATION_PATH:$PYTHONPATH

# Path to scripts
export PATH=$SCRIPTS_PATH:$PATH
