#!/bin/bash
export MICROMEGAS_HOME=$HOME/micromegas
export SCRIPTS_PATH=$MICROMEGAS_HOME/scripts
export MICROMEGAS_SCRIPTS_PATH=$MICROMEGAS_HOME/scripts
export MICROMEGAS_SIMULATION_PATH="$MICROMEGAS_HOME/simulation"
export MICROMEGAS_OUTPUT_PATH="/etapfs03/atlashpc/fneuhaus/micromegas"
export MICROMEGAS_RUN_PATH="$MICROMEGAS_HOME/simulation/runs"
export MICROMEGAS_RUN_DATABASE="$MICROMEGAS_HOME/simulation/runs/run_db.sqlite"


export PARTICLECONVERSION_EXEC=$MICROMEGAS_HOME/simulation/particleconversion/build/particleconversion
export DRIFT_EXEC=$MICROMEGAS_HOME/simulation/drift/drift
export AVALANCHE_EXEC=$MICROMEGAS_HOME/simulation/avalanche/avalanche

# Load cmake
module load devel/CMake/3.8.0

# Initialize ROOT
source ~/software/root-v6.10.06/gcc_6.3.0/bin/thisroot.sh

# Initialize python
workon sim

# Initialize GCC
export CC=$(which gcc)
export CXX=$(which g++)
export FC=$(which gfortran)

# Initialize GEANT4
module load own/geant4/current

# Initialize garfield
module load own/garfield/current

# Elmer
module load own/elmerfem/current

# gmsh
module load own/gmsh/current

# Pythonpath
export PYTHONPATH=$MICROMEGAS_SIMULATION_PATH:$PYTHONPATH

# Path to scripts
export PATH=$SCRIPTS_PATH:$PATH
