#!/bin/bash

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
   echo "Usage: $(basename $0) DATA_DIRECTORY (RUN_DIRECTORY)"
   exit 1
fi

# ROOT and Garfield++ setup
[[ ! -e "$AVALANCHE_EXEC" ]] && source $(dirname `readlink -f $0`)/init

WD="$(readlink -f $1)"
if [ "$#" -eq 2 ]; then
   echo $2
   cd $2
   export AVALANCHE_EXEC="$2/avalanche"
fi

echo "Using simulation directory: $WD"

if [ ! -d "$WD" ]; then
   echo "Input directory: $WD does not exist!"
   exit 1
fi

# GNU Parallel
module load software/gnu_parallel

# run parallel on all split files
# needs about ?M RAM per job
find ${WD} -regextype posix-egrep -regex '^.*[0-9]+_drift.root$' | sed -nE 's|(.*)/([0-9]+)_drift\.root|\1 \2|p' | parallel --colsep " " -j 64 --delay 1 --progress --no-notice "$AVALANCHE_EXEC {1}/{2}_drift.root {1}/{2}_avalanche.root > {1}/{2}_avalanche.log"

STATUS=$?
exit $STATUS

