#!/bin/bash

if [ "$#" -lt 2 ]; then
	echo "Usage: $(basename $0) DEST_FILE SOURCE_FILE [SOURCE_FILE]"
	exit 1
fi

# ROOT and Garfield++ setup
[[ ! -e "$ROOTSYS" ]] && source $(dirname `readlink -f $0`)/init

$ROOTSYS/bin/hadd -f $@

STATUS=$?
exit $STATUS

