#!/bin/bash

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
   echo "Usage: $(basename $0) FILENAME (NUMBER OF SPLITS)"
   exit 1
fi

# ROOT and Garfield++ setup
[[ ! -e "$DRIFT_EXEC" ]] && source $(dirname `readlink -f $0`)/init

INPUT_FILE="$1"
WD=`dirname $INPUT_FILE`

# Number of splits (use 64 as default)
NUM_SPLITS=64
if [ "$#" -eq 2 ]; then
   NUM_SPLITS=$2
fi

SPLIT_SCRIPT="$SCRIPTS_PATH/splitFile.py"

echo "Using simulation directory: $WD"

if [ ! -e "$INPUT_FILE" ]; then
   echo "Input file: $INPUT_FILE does not exist!"
   exit 1
fi

$SPLIT_SCRIPT -j $NUM_SPLITS $INPUT_FILE > $WD/split.log

STATUS=$?
exit $STATUS

