#!/bin/bash

JOB_DIR=/localscratch/$SLURM_JOBID

if [ "$#" -eq 0 ]; then
   echo "Usage: $(basename $0) RUN_DIRECTORY INPUT_FILES"
   exit 1
fi

# ROOT and Garfield++ setup
[[ ! -e "$AVALANCHE_EXEC" ]] && source $(dirname `readlink -f $0`)/init

# Get working directory and set executable path
WD="$(readlink -f $1)"
cd $WD
export AVALANCHE_EXEC="$WD/avalanche"

# Shift parameters so only files are in list now
shift
OUTPUT_DIR=`dirname $1`

echo "Using simulation directory: $WD"

# GNU Parallel
module load tools/parallel/20170622

# run parallel on all given files
# needs about ?M RAM per job
{ for f in $*; do
   filename=`basename $f`
   echo $f $JOB_DIR/${filename/_drift/_avalanche} $JOB_DIR/${filename/_drift.root/_avalanche.log}
done
} | parallel --colsep " " -j $# --delay 1 --no-notice "$AVALANCHE_EXEC {1} {2} > {3}"


# Copy logs and output files to data directory
cp $JOB_DIR/*.log $OUTPUT_DIR/
cp $JOB_DIR/*.root $OUTPUT_DIR/

STATUS=$?
exit $STATUS

