#!/bin/bash

JOB_DIR=/localscratch/$SLURM_JOBID

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
   echo "Usage: $(basename $0) DATA_DIRECTORY (RUN_DIRECTORY)"
   exit 1
fi

# ROOT and Garfield++ setup
[[ ! -e "$DRIFT_EXEC" ]] && source $(dirname `readlink -f $0`)/init

WD="$(readlink -f $1)"
if [ "$#" -eq 2 ]; then
   echo $2
   cd $2
   export DRIFT_EXEC="$2/drift"
fi

echo "Using simulation directory: $WD"
if [ ! -d "$WD" ]; then
   echo "Input directory: $WD does not exist!"
   exit 1
fi

# GNU Parallel
module load tools/parallel/20170622

# run parallel on all split files
# needs about 330M RAM per job
find ${WD} -regextype posix-egrep -regex '^.*[0-9]+_particleconversion\.root$' | sed -nE 's|(.*)/([0-9]+)_particleconversion\.root|\1 \2|p' | parallel --colsep " " -j 64 --delay 1 --progress --no-notice "$DRIFT_EXEC {1}/{2}_particleconversion.root {1}/{2}_drift.root > $JOB_DIR/{2}_drift.log"

cp $JOB_DIR/*.log $WD/

STATUS=$?
exit $STATUS

